SET PAGESIZE 100
SET LINESIZE 200
SET FEEDBACK OFF
SET HEADING ON
SET VERIFY OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ITPOWN;

PROMPT === ROLE_COUNTS ===
SELECT ATH_ID, COUNT(DISTINCT ENO) AS USER_COUNT
  FROM TPRMPP_CROLEI
 WHERE DEL_YN = 'N'
   AND NVL(USE_YN, 'Y') = 'Y'
   AND ATH_ID IN ('ITPAD001', 'ITPAD002', 'ITPZZ001')
 GROUP BY ATH_ID
 ORDER BY ATH_ID;

PROMPT === ELIGIBLE_PROJECT_COUNTS ===
SELECT COUNT(*) AS ELIGIBLE_TOTAL,
       NVL(SUM(CASE WHEN EXISTS (
             SELECT 1
               FROM TPRMPP_BITEMM i
              WHERE i.ABUS_MNG_NO = p.ABUS_MNG_NO
                AND i.SECT_SYS_UTZ_YN = 'Y'
                AND i.DEL_YN = 'N'
           ) THEN 1 ELSE 0 END), 0) AS INFOSEC_ELIGIBLE
  FROM TPRMPP_BPROJM p
  JOIN TPRMPP_BPROJA ps
    ON ps.ABUS_MNG_NO = p.ABUS_MNG_NO
   AND ps.CNCD_RFR_NO = p.ABUS_MNG_NO
   AND ps.DEL_YN = 'N'
  LEFT JOIN TPRMPP_BASCTM a
    ON a.ABUS_MNG_NO = p.ABUS_MNG_NO
   AND a.SNO = p.SNO
   AND a.DEL_YN = 'N'
 WHERE p.DEL_YN = 'N'
   AND ps.IT_PTL_STS_TC = '09'
   AND a.IT_PTL_ASCT_ID IS NULL;

PROMPT === OWNER_ACCOUNT_COVERAGE ===
SELECT COUNT(DISTINCT p.SVN_DPM_C) AS ELIGIBLE_DEPARTMENTS,
       COUNT(DISTINCT CASE WHEN u.ENO IS NOT NULL THEN p.SVN_DPM_C END)
           AS DEPARTMENTS_WITH_ACTIVE_USER
  FROM TPRMPP_BPROJM p
  JOIN TPRMPP_BPROJA ps
    ON ps.ABUS_MNG_NO = p.ABUS_MNG_NO
   AND ps.CNCD_RFR_NO = p.ABUS_MNG_NO
   AND ps.DEL_YN = 'N'
  LEFT JOIN TPRMPP_BASCTM a
    ON a.ABUS_MNG_NO = p.ABUS_MNG_NO
   AND a.SNO = p.SNO
   AND a.DEL_YN = 'N'
  LEFT JOIN TPRMPP_CUSERI u
    ON u.BBR_C = p.SVN_DPM_C
   AND u.DEL_YN = 'N'
 WHERE p.DEL_YN = 'N'
   AND ps.IT_PTL_STS_TC = '09'
   AND a.IT_PTL_ASCT_ID IS NULL;

PROMPT === ACTIVE_COUNCIL_STATUS_COUNTS ===
SELECT IT_PTL_ASCT_PRG_STS_TC AS STATUS_CODE, COUNT(*) AS COUNCIL_COUNT
  FROM TPRMPP_BASCTM
 WHERE DEL_YN = 'N'
 GROUP BY IT_PTL_ASCT_PRG_STS_TC
 ORDER BY IT_PTL_ASCT_PRG_STS_TC;

EXIT SUCCESS
